# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sasamin4ik\Desktop\11\menu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Menu_bg = QtWidgets.QLabel(self.centralwidget)
        self.Menu_bg.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.Menu_bg.setText("")
        self.Menu_bg.setPixmap(QtGui.QPixmap(":/21.png"))
        self.Menu_bg.setObjectName("Menu_bg")
        self.Continue_Game_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Continue_Game_Button.setGeometry(QtCore.QRect(90, 50, 361, 71))
        self.Continue_Game_Button.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    color: rgb(255, 255, 255, );\n"
"    font:55pt \"daylin\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, );\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}")
        self.Continue_Game_Button.setObjectName("Continue_Game_Button")
        self.New_Gamee_Button = QtWidgets.QPushButton(self.centralwidget)
        self.New_Gamee_Button.setGeometry(QtCore.QRect(70, 110, 361, 71))
        self.New_Gamee_Button.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    color: rgb(255, 255, 255, );\n"
"    font:55pt \"daylin\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, );\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}")
        self.New_Gamee_Button.setObjectName("New_Gamee_Button")
        self.Gallery_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Gallery_Button.setGeometry(QtCore.QRect(70, 180, 361, 71))
        self.Gallery_Button.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    color: rgb(255, 255, 255, );\n"
"    font:55pt \"daylin\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, );\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}")
        self.Gallery_Button.setObjectName("Gallery_Button")
        self.Settings_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Settings_Button.setGeometry(QtCore.QRect(80, 250, 361, 71))
        self.Settings_Button.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    color: rgb(255, 255, 255, );\n"
"    font:55pt \"daylin\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, );\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}")
        self.Settings_Button.setObjectName("Settings_Button")
        self.Exit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_Button.setGeometry(QtCore.QRect(70, 310, 361, 71))
        self.Exit_Button.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgba(0, 0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 55pt \"daylin\";\n"
"    border-radius: 10px;\n"
"    box-shadow: 0 0 10px rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}\n"
"")
        self.Exit_Button.setObjectName("Exit_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "game"))
        self.Continue_Game_Button.setText(_translate("MainWindow", "Continue Game"))
        self.New_Gamee_Button.setText(_translate("MainWindow", "New Game"))
        self.Gallery_Button.setText(_translate("MainWindow", "Gallery"))
        self.Settings_Button.setText(_translate("MainWindow", "Settings"))
        self.Exit_Button.setText(_translate("MainWindow", "Exit"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
